org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
# IntelliJ IDEA compatibility with configuration cache
org.gradle.configuration-cache=false

# Mod metadata (used in fabric.mod.json and build)
mod.group=com.github.minecraftschurlimods
mod.id=bibliocraft
mod.version=1.1.0
mod.name=Bibliocraft Legacy
mod.vendor=MinecraftschurliMods
mod.authors=IchHabeHunger54, Minecraftschurli
mod.credits=Nuchaz (original mod author), XFactHD (help with models), the Fabric community (overall help)
mod.logo=logo.png
mod.description=Bibliocraft Legacy is a port of the original BiblioCraft Minecraft mod by Nuchaz. It adds various pieces of decorative and functional furniture into the game.
mod.url=https://www.curseforge.com/minecraft/mc-mods/bibliocraft-legacy

java_version=21

github.owner=MinecraftschurliMods
github.repo=Bibliocraft-Legacy

license.name=MIT
license.url=https://opensource.org/licenses/MIT

# Fabric (see https://fabricmc.net/develop)
minecraft_version=1.21.1
loader_version=0.16.9
loom_version=1.14.9
fabric_version=0.116.4+1.21.1

# Maven / archives
maven_group=com.github.minecraftschurlimods
archives_base_name=bibliocraftfabric

# Optional dependencies (JEI, etc.)
dependency.jei.version=19.21.0.246
dependency.jei.version.range=[19,20)

junit_version=5.7.1

mc-publish.curseforge=1122260
mc-publish.modrinth=eiXYWB7J
