org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod.group=at.minecraftschurli.mods
mod.id=bibliocraft
mod.version=26.2-1.0.0
mod.name=Bibliocraft Legacy
mod.authors=Astryxion
mod.credits=Nuchaz, XFactHD, IchHabeHunger54, Minecraftschurli
mod.logo=logo.png
mod.description=Bibliocraft Legacy is a port of the original BiblioCraft Minecraft mod by Nuchaz. It adds various pieces of decorative and functional furniture into the game.
mod.url=https://www.curseforge.com/minecraft/mc-mods/bibliocraft-legacy-expanded
mod.archives.name=bibliocraftlegacyfabric

java_version=25

github.owner=astryxion
github.repo=BiblioCraft-Legacy-Expanded

license.name=MIT
license.url=https://opensource.org/licenses/MIT

mc_version=26.2
mc_version_range=[26.2,)

loader_version=0.19.3
fabric_version=0.152.2+26.2
loom_version=1.17-SNAPSHOT
neo_version=26.2.0.0-beta

dependency.jei.version=30.1.0.10
dependency.jei.version.range=[30.1,31)

junit_version=5.7.1

mc-publish.curseforge=1122260
mc-publish.modrinth=eiXYWB7J
